baseURL = "http://example.org/"
languageCode = "en-nz"
title = "PVC TL"

theme = "niello"

[taxonomies]
    tag = 'tags'
    translator = 'translator'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[permalinks]
    novel = "/novel/:slug/:filename"
    page = "/:filename"

[params]
    keywords = "novels, bl, chinese translation"
    description = "Chinese BL novel translations, primarily involving the protagonist, villain and cannon fodder (PVC)"
    copyright = "&#xA9; 2021 PVC TL"
    google_ad_client = "ca-pub-******"
    ga = "UA-******"

[menu]
    [[menu.niello]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.niello]]
    name = "Novels"
    url = "/novel/"
    weight = 2

    [[menu.niello]]
    name = "About"
    url = "/about/"
    weight = 3
