baseURL = "https://pvc-tl.netlify.app/"
languageCode = "en-nz"
title = "PVC TL"

theme = "niello"

disablePathToLower = true

[taxonomies]
    tag = 'tags'
    translator = 'translator'

[permalinks]
    novel = "/novel/:slug/:filename"
    page = "/:filename"

[params]
    keywords = "novels, bl, chinese translation"
    description = "Chinese BL novel translations, primarily involving the protagonist, villain and cannon fodder (PVC)"
    copyright = "&#xA9; 2021 PVC TL"

[menu]
    [[menu.niello]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.niello]]
    name = "Novels"
    url = "/novel/"
    weight = 2

    [[menu.niello]]
    name = "Terms"
    url = "/common-tl/"
    weight = 3

    [[menu.niello]]
    name = "Other"
    url = "/about/"
    weight = 4

[markup]
    [markup.highlight]
        style = 'native'
        linenos = true